server:
  port: 8082

spring:
  application:
    name: badmintonepic

  datasource:

    url: jdbc:postgresql://localhost:5434/badminton_epic?currentSchema=public
    username: postgres     # 你的数据库账号
    password: 123456  # 你的数据库密码
    driver-class-name: org.postgresql.Driver
mybatis-plus:
  configuration:
    # 开启驼峰转下划线（重要：Java 的 offense 会对应数据库的 offense）
    map-underline-to-camel-case: true
  global-config:
    db-config:
      id-type: auto # 对应数据库的 BIGSERIAL 自增